FROM ruby:latest

RUN apt-get update \
  && apt-get -y install man-db manpages manpages-dev vim git less zip gzip build-essential gcc g++ make sqlite3 \
  && rm -rf /var/lib/apt/lists/*

# install yarn
# curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
#     echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
#     apt-get update && apt-get install yarn

RUN mkdir -p /apps/entrustody

WORKDIR /apps/entrustody

ENV GEM_HOME="/gems"
ENV BUNDLE_PATH="/gems"

EXPOSE 3000
EXPOSE 3001

CMD /bin/bash
